project:
  type: website

website:
  title: "Group 7"
  navbar:
    left:
      - href: overview.html
        text: Overview
      - href: approach.html
        text: Approach
      - href: eda.html
        text: Data Analysis
      - href: reports.html
        text: Matching Reports
      - href: southseafood.html
        text: SouthSeaFood Express
      - href: Path.html
        text: Visualising IUU  
      - href: newbehaviours.html
        text: IUU Behaviours  
      - href: Project_Proposal.html
        text: Proposal
      - href: guide.html
        text: User Guide
      
format:
  html:
    page-layout: full
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

