---
title: "Data Analysis"

date-modified: "last-modified" 
execute:   
  eval: true   
  echo: true   
  warning: false   
  freeze: true 
  
format:
  html:
    toc: false
---

# Understanding the Oceanus Fishing Industry

To understand IUU behaviors, we must first identify baseline behaviors, enabling us to detect anomalies within the vast sea of data. To help the analysts establish baseline understanding of Oceanus Fishing Industry, the following data exploration application will enable understanding the following:

1.  Dwell time by location and vessel type, with tooltip to show Vessel Name, Company, Tonnage, Length, Dwell Time, Type of Vessel, and the date that the vessel is at the selected location. By this exploration, we are able to pin point certain vessels that have excessive dwell time in certain locations, where excessive dwell could be a sign of IUU.

2.  Cargo in quantity ton, with selector for location, fish species and the selected date for comparison. The default date is set to 14 May 2035, the postulated date that Southseafood Express Corp was caught and ceased operation. The comparison before and after allows the analyst to understand the changes in delivery behaviour at the ports.

3.  Monthly visits, with selector of locations, enable analyst to know the mean and median visit frequency in the selected locations, as well as have an overview of the visit frequency through the months. Through this visualisation, analyst will be able to identify period of peak or trough against it mean and median.

<iframe src="https://hr6p23-xiuhao-liang.shinyapps.io/ShinyDemo/" width="100%" height="800px" frameborder="0">

</iframe>
