---
title: "Visualising IUU Fishing through Paths"
date-modified: "last-modified" 

execute:   
  eval: true   
  echo: true   
  warning: false   
  freeze: true 

format:
  html:
    toc: false
---

# Understanding IUU - Dwell Times and Path

## Overview and Guide

To better visualise the IUU behaviours of the fishing vessels, we can first compare the dwell times of the vessels at the various location.

### Compare Dwell Times

This is done through the first tab - "Compare Dwell Times", where users can select the Company, Vessels and Location Type. To look at specific areas, such as Nemo Reef etc, users can next specify the actual location (or source) for the comparison.

An additional filter is available to filter the vessels by their tonnage, so that we can compare vessels of the same types.

### Plot Path of Vessels (Single or Multiple) 

After we have a better understanding of the vessels, we can plot their paths using either Single Vessel or Multiple Vessels. Users are able to select the size of the dwell time (which affects the size of the circle), the time range of data to be shown, and to specify the colours of the path. This will help us to visualise the paths of the various vessels, and where they lingered more than usual. The width of the path can also be specified by the user through the Trajetory Linewidth option.

## ShinyApp - Path Plotter

<iframe src="https://zjjgithub.shinyapps.io/PathPlotter/" width="100%" height="800px" frameborder="0">

</iframe>
